//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMathsOperation")]
public interface IMathsOperation
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperation/add", ReplyAction="http://tempuri.org/IMathsOperation/addResponse")]
    int add(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperation/add", ReplyAction="http://tempuri.org/IMathsOperation/addResponse")]
    System.Threading.Tasks.Task<int> addAsync(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperation/multiply", ReplyAction="http://tempuri.org/IMathsOperation/multiplyResponse")]
    int multiply(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathsOperation/multiply", ReplyAction="http://tempuri.org/IMathsOperation/multiplyResponse")]
    System.Threading.Tasks.Task<int> multiplyAsync(int a, int b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMathsOperationChannel : IMathsOperation, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MathsOperationClient : System.ServiceModel.ClientBase<IMathsOperation>, IMathsOperation
{
    
    public MathsOperationClient()
    {
    }
    
    public MathsOperationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MathsOperationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathsOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MathsOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int add(int a, int b)
    {
        return base.Channel.add(a, b);
    }
    
    public System.Threading.Tasks.Task<int> addAsync(int a, int b)
    {
        return base.Channel.addAsync(a, b);
    }
    
    public int multiply(int a, int b)
    {
        return base.Channel.multiply(a, b);
    }
    
    public System.Threading.Tasks.Task<int> multiplyAsync(int a, int b)
    {
        return base.Channel.multiplyAsync(a, b);
    }
}
