//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorGUI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMonitorService")]
    public interface IMonitorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/NbRequest", ReplyAction="http://tempuri.org/IMonitorService/NbRequestResponse")]
        int NbRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/NbRequest", ReplyAction="http://tempuri.org/IMonitorService/NbRequestResponse")]
        System.Threading.Tasks.Task<int> NbRequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/AverageExecTime", ReplyAction="http://tempuri.org/IMonitorService/AverageExecTimeResponse")]
        long AverageExecTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorService/AverageExecTime", ReplyAction="http://tempuri.org/IMonitorService/AverageExecTimeResponse")]
        System.Threading.Tasks.Task<long> AverageExecTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorServiceChannel : MonitorGUI.ServiceReference1.IMonitorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorServiceClient : System.ServiceModel.ClientBase<MonitorGUI.ServiceReference1.IMonitorService>, MonitorGUI.ServiceReference1.IMonitorService {
        
        public MonitorServiceClient() {
        }
        
        public MonitorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NbRequest() {
            return base.Channel.NbRequest();
        }
        
        public System.Threading.Tasks.Task<int> NbRequestAsync() {
            return base.Channel.NbRequestAsync();
        }
        
        public long AverageExecTime() {
            return base.Channel.AverageExecTime();
        }
        
        public System.Threading.Tasks.Task<long> AverageExecTimeAsync() {
            return base.Channel.AverageExecTimeAsync();
        }
    }
}
